//
// Created by Shiwo on 3/10/2022.
//

#ifndef CHRISTMASLIGHTS_DUALCOLOURTRANSITION_H
#define CHRISTMASLIGHTS_DUALCOLOURTRANSITION_H

void dualColourTransition();

#endif //CHRISTMASLIGHTS_DUALCOLOURTRANSITION_H
