//
// Created by Shiwo on 3/10/2022.
//

#ifndef CHRISTMASLIGHTS_INDIVIDUALCHASESWEEP_H
#define CHRISTMASLIGHTS_INDIVIDUALCHASESWEEP_H

void individualChaseSweep();

#endif //CHRISTMASLIGHTS_INDIVIDUALCHASESWEEP_H
