//
// Created by Shiwo on 3/10/2022.
//

#ifndef CHRISTMASLIGHTS_SMOOTHINDIVIDUALCHASE_H
#define CHRISTMASLIGHTS_SMOOTHINDIVIDUALCHASE_H

void smoothIndividualChase();

#endif //CHRISTMASLIGHTS_SMOOTHINDIVIDUALCHASE_H
